### ISSUE TITLE
Post-quantum cryptography underlying mathematical problems

### ISSUE THREAD

**Issue by claucece** [tireddy2/pqc-for-engineers#16]
The statement:

```
The current set of problems used in post-quantum cryptography can be currently grouped into three different categories: lattice-based, hash-based and code-based.
```

is not completely accurate, as it is missing, for example, isogeny-based cryptography and multivariate-quadratic-based. If the paragraph only pertains to the "current" result of the PQC NIST process, then it should note that. If it refers to the "ongoing" PQC NIST signatures process, then it should include isogeny-based cryptography and multivariate-quadratic-based.

**Comment by auriee** [comment]
@claucece We had isogeny-based (SIKE) and multivariate-quadratic based (Rainbow) in the draft but we removed it after some comments were received that there are "currently" of either in the NIST PQC process as it may be more relevant to Engineers to know about this specifically.
We can add a line stating the above. Or we can provide a line or two on Isogeny and Multivariate. Please advise.

**Comment by claucece** [comment]
I think adding that they refer to the 'current' is good. I can send a PR ;)

**Comment by auriee** [comment]
@claucece Sounds good, send the PR. Thanks! :)

**Comment by auriee** [comment]
@claucece Will it be possible to send the PR before the weekend? We plan to submit the version -02 by this weekend.
