### ISSUE TITLE
Interactivity in PQC KEM and Diffie-Hellman (DH) Key Exchange

### ISSUE THREAD

**Issue by tireddy2** [tireddy2/pqc-for-engineers#21]
Comment from @ounsworth - I actually disagree with this section. *Authenticated* Key Exchange with KEMs -- ie where both parties contribute a KEM public key to the overall session key -- is necessarily interactive in the way described in this section (RIP Signal Protocol), but single-sided KEM, for example where one person has a KEM key in a certificate and the other person simply wants to encrypt for it, as in S/MIME or OpenPGP email, is perfectly doable with non-interactive HPKE (RFC9180), which is actually explaied in the next section. I suggest this section be re-worked: a) re-titled to "Authenticated Key Exchange", and b) explain why we love this property of DH, and why we're all it tears about losing it, I have added some text below the diagram to attempt to do this, but this needs another editing pass.

**Comment by auriee** [comment]
@ounsworth @tireddy2 - The changes have been made. Please see and approve/merge the changes back to main from this pull request: https://github.com/tireddy2/pqc-for-engineers/pull/22
