### ISSUE TITLE
LMS private key size

### ISSUE THREAD

**Issue by kriskwiatkowski** [tireddy2/pqc-for-engineers#47]
In the "LMS scheme - key and signature sizes" the private key size represents minimal amount of bytes to be used by LMS private key - it is a sum of bytes used by counter (q), identifier (I) and a seed.

In practice for the key to be useful by its own (i.e. for signing), the implementation needs values of OTS and LMS type codes, both 4 byte long. I think we should include type codes in the private key size also or document better what the value for private key size represents.

@kriskwiatkowski for you

**Comment by auriee** [comment]
@kriskwiatkowski Sure, raise a PR, I'll review and merge. As well one or two lines as on the dilithium topic we discussed.
