### ISSUE TITLE
Define "quantum ready" and "quantum secure"

### ISSUE THREAD

**Issue by ounsworth** [tireddy2/pqc-for-engineers#49]
I would like to propose definitions for “quantum resistant” and “quantum ready”.

A “quantum ready” system is one that is capable of interacting with peers using post-quantum cryptographic protocols. 
A “quantum resistant” or “quantum secure” is a system which is fully upgraded to use post-quantum cryptography for all internal security functions. 
To illustrate the difference, consider a device which supports PQC TLS ciphersuites, but whose firmware and secure-boot system uses only traditional cryptography. Such a system would be considered quantum ready but not quantum secure.

**Comment by kriskwiatkowski** [comment]
I don't think I agree. Such distinction makes the matter just more complicated ("quantum ready" and "quantum resistant" are very closely related terms)?

But indeed, it's a good point that there is a difference between quantum-resistant protocol and quantum-resistant computer systems.
