### ISSUE TITLE
Comment Set-3 (Only one comment)

### ISSUE THREAD

**Issue by auriee** [tireddy2/pqc-for-engineers#5]
I have one suggestion, would it help to describe how many qubits we expect to need in order to successfully run Shor's algorithm against different key lengths? This just to give some perspective to the reader.

**Comment by Dimitris-Schoinianakis** [comment]
I'm not sure how to address this per different key length. However, we can offer some standard references for attacking RSA-2048 (20M noisy qubits [1] in 8 hours or 4099 stable ones in 10 seconds [2])

[1] https://arxiv.org/abs/1905.09749
[2] https://www.quintessencelabs.com/blog/breaking-rsa-encryption-update-state-art/

**Comment by auriee** [comment]
Exactly, this is one example we presented during the TEO presentation. Is there any other reference you know have or know about that has some other good examples?

**Comment by Dimitris-Schoinianakis** [comment]
Not to my knowledge.

--
Best,
-δ
________________________________
